//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class needy_possible_time
    {
        public int needy_possible_time_code { get; set; }
        public int needy_details_code { get; set; }
        public int time_slot_code { get; set; }
    
        public virtual neediness_details neediness_details { get; set; }
        public virtual time_slot time_slot { get; set; }
    }
}
