//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organization()
        {
            this.managers = new HashSet<manager>();
            this.neediness_details = new HashSet<neediness_details>();
            this.volunteering_details = new HashSet<volunteering_details>();
        }
    
        public int org_code { get; set; }
        public string org_name { get; set; }
        public string org_platform { get; set; }
        public bool need_scheduling { get; set; }
        public int org_min_age { get; set; }
        public System.DateTime activity_start_date { get; set; }
        public System.DateTime activity_end_date { get; set; }
        public int avg_volunteering_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manager> managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neediness_details> neediness_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<volunteering_details> volunteering_details { get; set; }
    }
}
