//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public volunteer()
        {
            this.volunteering_details = new HashSet<volunteering_details>();
        }
    
        public string volunteer_ID { get; set; }
        public string volunteer_full_name { get; set; }
        public string volunteer_address { get; set; }
        public string volunteer_phone { get; set; }
        public string volunteer_email { get; set; }
        public string volunteer_password { get; set; }
        public System.DateTime volunteer_birth_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<volunteering_details> volunteering_details { get; set; }
    }
}
